version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node
    ports:
     - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'AKIA4HG3LGU4PIIH2WX2'
      AWS_SECRET_ACCESS_KEY: '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'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region ap-south-1